//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        [Display(Name = "#")]
        public int id { get; set; }
        [Display(Name = "Rut")]
        [Required(ErrorMessage = "El rut es requerido")]
        public string rut { get; set; }
        [Display(Name = "Razón Social")]
        [Required(ErrorMessage = "La razón social es requerida")]
        public string razonSocial { get; set; }
        [Display(Name = "Ciudad")]
        [Required(ErrorMessage = "La ciudad es requerida")]
        public Nullable<int> CiudadId { get; set; }

        public virtual Ciudad Ciudad { get; set; }
    }
}
